// Generated by CoffeeScript 1.6.3
(function() {
  var BaiduPlatform, baidu, crypto, request, _;

  _ = require('underscore');

  request = require('request');

  crypto = require('crypto');

  BaiduPlatform = (function() {
    var ksort, urlencode;

    BaiduPlatform.prototype.host = 'http://channel.api.duapp.com';

    BaiduPlatform.prototype.apiUri = '/rest/2.0/channel/channel';

    BaiduPlatform.prototype.apiMethod = 'POST';

    function BaiduPlatform() {
      this.apiKey = '';
      this.apiSecret = '';
    }

    urlencode = function(str) {
      return encodeURIComponent(str).replace(/!/g, '%21').replace(/'/g, '%27').replace(/\(/g, '%28').replace(/\)/g, '%29').replace(/\*/g, '%2A').replace(/%20/g, '+');
    };

    ksort = function(obj) {
      var k, keys, _i, _len, _obj;
      keys = _.keys(obj);
      keys.sort(function(x, y) {
        return x > y;
      });
      _obj = {};
      for (_i = 0, _len = keys.length; _i < _len; _i++) {
        k = keys[_i];
        _obj[k] = obj[k];
      }
      return _obj;
    };

    BaiduPlatform.prototype.errorCallback = function(err) {
      return console.error("BAIDU-ERROR: ", err);
    };

    BaiduPlatform.prototype.configure = function(options) {
      var key, val;
      if (options == null) {
        options = {};
      }
      for (key in options) {
        val = options[key];
        this[key] = val;
      }
      return this;
    };

    BaiduPlatform.prototype.sign = function(params) {
      var k, paramsStr, rawStr, url, v;
      url = this.host + this.apiUri;
      params = ksort(params);
      paramsStr = ((function() {
        var _results;
        _results = [];
        for (k in params) {
          v = params[k];
          _results.push("" + k + "=" + v);
        }
        return _results;
      })()).join('');
      rawStr = urlencode("" + this.apiMethod + url + paramsStr + this.apiSecret);
      return crypto.createHash('md5').update(rawStr).digest('hex');
    };

    BaiduPlatform.prototype.send = function(data, callback) {
      if (data == null) {
        data = {};
      }
      if (callback == null) {
        callback = function() {};
      }
      data.apikey = this.apiKey;
      data.method || (data.method = 'push_msg');
      data.push_type || (data.push_type = 3);
      data.timestamp = Math.round(Date.now() / 1000);
      data.sign = this.sign(data);
      return request({
        uri: this.host + this.apiUri,
        method: this.apiMethod,
        form: data
      }, function(err, res, body) {
        return callback(err, body);
      });
    };

    return BaiduPlatform;

  })();

  baidu = new BaiduPlatform;

  baidu.BaiduPlatform = BaiduPlatform;

  module.exports = baidu;

}).call(this);
