// Generated by CoffeeScript 1.6.3
(function() {
  var BaiduPlatform, crypto;

  crypto = require('crypto');

  BaiduPlatform = (function() {
    var urlencode;

    function BaiduPlatform() {}

    urlencode = function(str) {
      return encodeURIComponent(str).replace(/!/g, '%21').replace(/'/g, '%27').replace(/\(/g, '%28').replace(/\)/g, '%29').replace(/\*/g, '%2A').replace(/%20/g, '+');
    };

    BaiduPlatform.prototype.sign = function(method, url, params, secret) {
      var k, paramsStr, rawStr, v;
      paramsStr = ((function() {
        var _results;
        _results = [];
        for (k in params) {
          v = params[k];
          _results.push("" + k + "=" + v);
        }
        return _results;
      })()).join('');
      rawStr = urlencode("" + method + url + paramsStr + secret);
      return crypto.createHash('md5').update(rawStr).digest('hex');
    };

    return BaiduPlatform;

  })();

  module.exports = BaiduPlatform;

}).call(this);
