// Generated by CoffeeScript 1.6.3
(function() {
  var Pusher, exports, push, utils, _;

  _ = require('underscore');

  utils = require('./utils');

  Pusher = (function() {
    function Pusher() {}

    Pusher.prototype.configure = function(options) {
      var conf, paths, serv;
      paths = utils.findBackendPathByServName(_.keys(options));
      for (serv in options) {
        conf = options[serv];
        if (paths[serv]) {
          push[serv] = require("./" + paths[serv]).configure(conf);
        }
      }
      return push;
    };

    return Pusher;

  })();

  push = new Pusher;

  exports = module.exports = push;

}).call(this);
