// Generated by CoffeeScript 1.8.0
(function() {
  var Pusher, exports, push, _;

  _ = require('underscore');

  Pusher = (function() {
    function Pusher() {}

    Pusher.prototype.configure = function(options) {
      var conf, e, serv;
      for (serv in options) {
        conf = options[serv];
        try {
          push[serv] = require("./platforms/" + serv).configure(conf);
        } catch (_error) {
          e = _error;
        }
      }
      return push;
    };

    return Pusher;

  })();

  push = new Pusher;

  exports = module.exports = push;

}).call(this);
