// Generated by CoffeeScript 1.8.0
(function() {
  var Push, push;

  Push = (function() {
    function Push() {}

    Push.prototype.init = function(options) {
      this.options = options;
    };

    Push.prototype.push = function() {};

    return Push;

  })();

  push = new Push;

  push.Push = Push;

  module.exports = push;

}).call(this);
